version: "3.9"
services:
  redis:
    container_name: redis-micropython-workshop
    image: redis/redis-stack:7.2.0-RC3
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure