title: MicroPython Workshop
email: simon@crudworks.org
description: >- 
  A workshop using the Raspberry Pi Pico W and Pimoroni GFX Pack.
baseurl: "/micropython-workshop/"
url: "https://simonprickett.dev"
twitter_username: simon_prickett 
github_username:  simonprickett
repository: simonprickett/micropython-workshop
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
plugins:
  - jekyll-remote-theme
